# Generated by Django 4.0.4 on 2022-11-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Type Housing',
                'verbose_name_plural': 'Types housing',
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=55)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.typehousing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Housing',
            },
        ),
    ]
