# Generated by Django 4.0.4 on 2022-11-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='user',
        ),
    ]
