# Generated by Django 4.0.4 on 2022-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_housing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
