# Generated by Django 4.0.4 on 2022-11-10 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_housing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 18, 5, 17, 970296, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='housing',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Deleted Date'),
        ),
        migrations.AddField(
            model_name='housing',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='housing',
            name='state',
            field=models.BooleanField(default=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
