# Generated by Django 4.0.4 on 2022-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_housing_created_date_housing_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
