# Generated by Django 4.0.4 on 2022-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_housing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
