# Generated by Django 4.0.4 on 2022-11-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('housing', '0011_housing_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='department',
        ),
        migrations.AddField(
            model_name='housing',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.cityubication'),
        ),
    ]
