# Generated by Django 4.0.4 on 2022-11-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_remove_housing_department_housing_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='city',
            new_name='department',
        ),
    ]
