# Generated by Django 4.0.4 on 2022-12-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0013_rename_city_housing_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.typehousing'),
        ),
    ]
