# Generated by Django 4.0.4 on 2023-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0014_rename_adress_housing_address_alter_housing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='state',
        ),
        migrations.AddField(
            model_name='housing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
