# Generated by Django 4.0.4 on 2023-01-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0017_remove_housing_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
