# Generated by Django 4.0.4 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateUbication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted Date')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
