# Generated by Django 4.0.4 on 2022-11-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateubication',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
    ]
