# Generated by Django 4.0.4 on 2022-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_alter_stateubication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateubication',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
