# Generated by Django 4.0.4 on 2023-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_remove_stateubication_state_stateubication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateubication',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
