# Generated by Django 4.0.4 on 2023-01-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_stateubication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateubication',
            name='token',
        ),
    ]
