# Generated by Django 4.0.4 on 2022-11-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_basemodel_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
