# Generated by Django 4.0.4 on 2022-11-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
