# Generated by Django 4.0.4 on 2023-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_cityubication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityubication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
