# Generated by Django 4.0.4 on 2023-01-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_cityubication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityubication',
            name='token',
        ),
    ]
